services:
  - type: worker
    name: helpcxc
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PYTHONUNBUFFERED
        value: 1
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: bot-data
      mountPath: /app/data
      sizeGB: 1
